name: biosignal
channels:
    - conda-forge
    - defaults
dependencies:
    - cudatoolkit=11.8
    - python=3.11
    - pip=23.3
    - pip:
          - mne==1.6.0
          - wfdb==4.1.2
          - numpy==1.26.3
          - matplotlib==3.8.2
          - --extra-index-url https://pypi.nvidia.com
          - tensorflow[and-cuda]==2.15.0
