name: tf11
channels:
    - conda-forge
    - defaults
dependencies:
    - cudnn=8.1
    - cudatoolkit=11.2
    - python=3.10
    - pip=23.3
    - pip:
          - mne==1.6.0
          - wfdb==4.1.2
          - matplotlib==3.8.2
          - tensorflow==2.11.1
variables:
    LD_LIBRARY_PATH: /home/mhnemati/miniconda3/envs/biosignal/lib
